website/accounts/urls.py
from django.urls import path

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'accounts'

urlpatterns = [
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

website/web_app/urls.py
from django.urls import path

from . import views
from .views import ArticlesListView, ArticlesDetailView, ArticlesCreateView, ArticlesUpdateView, ArticlesDeleteView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'web_app'
urlpatterns = [

    # path('recipe_list', views.recipe_list, name='recipe_list'),
    path('recipe_list', views.RecipeListView.as_view(), name='recipe_list'),
    path('articles_list', views.ArticlesListView.as_view(), name='articles_list'),
    path('articles_list/<str:username>', views.UserArticlesListView.as_view(), name='user_articles_list'),
    path('category_create', views.category_create, name="category_create"),
    path('articles_create', views.ArticlesCreateView.as_view(), name="articles_create"),
    path('<int:pk>/update', views.ArticlesUpdateView.as_view(), name='articles_update'),
    path('<int:pk>/delete', views.ArticlesDeleteView.as_view(), name='articles_delete'),
    path('<int:pk>/comment', views.add_comment_to_articles, name='articles_comment'),
    path('recipe_create', views.recipe_create, name="recipe_create"),
    path('<int:pk>', views.ArticlesDetailView.as_view(), name='articles_detail'),
    path('recipe_list/<int:pk>', views.RecipeDetailView.as_view(), name='recipe_detail'),

]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from web_app import views as web_app
from accounts import views as account

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('', include("web_app.urls")),
    # path('', web_app.articles_list),

    path('', web_app.ArticlesListView.as_view()),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/web_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse, reverse_lazy


class Recipe(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    image = models.ImageField(default="default.png", blank=True)
    ingredients = models.TextField()
    preparation = models.TextField()

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(default="default.png", blank=True)

    def __str__(self):
        return self.title


# Create your models here.
class Articles(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default="default.png", blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.slug

    def snippet(self):
        return self.body[:200] + '  ...'

    def get_absolute_url(self):
        return reverse("web_app:articles_detail", kwargs={'pk': self.pk})


class Comments(models.Model):
    article = models.ForeignKey(Articles, related_name="comments",default=None, on_delete=models.CASCADE)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    approved_comment = models.BooleanField(default=False)

    def __str__(self):
        return self.body

    def get_absolute_url(self):
        return reverse("web_app:articles_detail", kwargs={'pk': self.pk})

    def comment_approved(self):
            self.approved_comment = True
            self.save()

website/web_app/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Articles
        fields = ['title', 'body', 'thumb', 'category',]


class CreateCategory(forms.ModelForm):
    class Meta:
        model = models.Category
        fields = ['title', 'image', ]


class CreateRecipe(forms.ModelForm):
    class Meta:
        model = models.Recipe
        fields = ['title', 'subtitle', 'image', 'ingredients', 'preparation']


class UpdateArticle(forms.ModelForm):
    class Meta:
        model = models.Articles
        fields = ['title', 'body', 'slug', 'category', 'recipe']


class CreateComment(forms.ModelForm):
    class Meta:
        model = models.Comments
        fields = ['author', 'body', ]

website/web_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Articles, Recipe, Category, Comments
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from accounts import views as acc
from . import forms
from django.contrib import messages
# Create your views here.
from django.views.generic import ListView, DeleteView, DetailView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.http import HttpResponse


#
# def articles_list(request):
#     articles = Articles.objects.all().order_by('-date')
#     return render(request, "articles_list.html", {'articles_list': articles})

class ArticlesListView(ListView):
    model = Articles
    template_name = "articles_list.html"
    context_object_name = "articles_list"
    ordering = ['-date']
    paginate_by = 4


class UserArticlesListView(ListView):
    model = Articles
    template_name = "user_articles_list.html"
    context_object_name = "user_articles_list"
    ordering = ['-date']
    paginate_by = 4

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Articles.objects.filter(author=user).order_by('-date')


class ArticlesDetailView(DetailView):
    model = Articles
    template_name = "articles_detail.html"
    context_object_name = "articles_detail"


class ArticlesCreateView(LoginRequiredMixin, CreateView):
    model = Articles
    fields = ['title', 'body', 'thumb', 'category', 'recipe']
    template_name = "articles_create.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticlesUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Articles
    fields = ['title', 'body', 'slug', 'thumb', 'category', 'recipe']
    template_name = "articles_create.html"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        article = self.get_object()
        if self.request.user == article.author:
            return True
        return False


class ArticlesDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Articles
    template_name = "articles_confirm_delete.html"
    context_object_name = "articles_delete"

    success_url = reverse_lazy('web_app:articles_list')

    def test_func(self):
        article = self.get_object()
        if self.request.user == article.author:
            return True
        return False


@login_required
def add_comment_to_articles(request, pk):
    article = get_object_or_404(Articles, pk=pk)
    if request.method == "POST":
        form = forms.CreateComment(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            return redirect('web_app:articles_detail', pk=article.pk)
    else:
        form = forms.CreateComment()
    return render(request, 'articles_comment.html', {'form': form})


@login_required(login_url="/accounts/login/")
def articles_create(request):
    if request.method == "POST":
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('web_app:articles_list')
    else:

        form = forms.CreateArticle()
    return render(request, "articles_create.html", {'form': form})


@login_required(login_url="/accounts/login/")
def category_create(request):
    if request.method == "POST":
        form = forms.CreateCategory(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('web_app:articles_list')
    else:

        form = forms.CreateCategory()
    return render(request, "category_create.html", {'form': form})


@login_required(login_url="/accounts/login/")
def recipe_create(request):
    if request.method == "POST":
        form = forms.CreateRecipe(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('web_app:articles_list')
    else:

        form = forms.CreateRecipe()
    return render(request, "recipe_create.html", {'form': form})


def recipe_list(request):
    recipes = Recipe.objects.all().order_by('title')
    return render(request, "recipe_list.html", {'recipes': recipes})

class RecipeListView(ListView):
    model = Recipe
    template_name = "recipe_list.html"
    context_object_name = "recipe_list"
    ordering = ['title']
    paginate_by = 4

class RecipeDetailView(DetailView):
    model = Recipe
    template_name = "recipe_detail.html"
    context_object_name = "recipe_detail"

website/web_app/templates/Homepage.html
{% extends "base.html" %}
{%  load static from staticfiles %}
{% block body_block %}
{% endblock %}

website/web_app/templates/articles_comment.html
{% extends "base.html" %}
{% block body_block %}


<div class="site-form">
    <h2>Create a new comment to an article</h2>
    <!--    enctyp is necessary due to the image upload field-->
    <form class="textarea" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        {{ form }}
        <input type="submit" value="create">
    </form>
</div>
<script src="/static/web_app/slugify.js"></script>
{% endblock %}

website/web_app/templates/articles_confirm_delete.html
{% extends "base.html" %}

{% block body_block %}
   <div class="articles">

        <div class="article">
            <div class="article-detail">
                <p><img src="{{articles_detail.category.image.url}}"></p>
                <p> Created on {{ object.date }} by {{ object.author }}</p>
                <hr>
                <h2>{{object.title}}</h2>
                <hr>
                <p>{{ object.snippet }}</p>

                 <form method="post">
                    {% csrf_token%}
                   <h2 style="color:#00dba0">Are you sure you want to delete </h2>
                     <h2>{{ object }}?</h2>


                    <input type="submit" class="btn btn-danger" value="Confirm">
                </form>


            </div>
        </div>
    </div>


</form>

{% endblock %}

website/web_app/templates/articles_create.html
{% extends "base.html" %}
{% block body_block %}


<div class="site-form">
    <h2>Create a new article to be posted</h2>
    <hr>
    <!--    enctyp is necessary due to the image upload field-->
    <form class="textarea" action="{% url 'web_app:articles_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        {{ form }}
        <input type="submit" value="create">
    </form>
</div>
<script src="/static/web_app/slugify.js"></script>
{% endblock %}

website/web_app/templates/articles_detail.html
{% extends "base.html" %}
{%  load static from staticfiles %}
{% block body_block %}


<!--<h1 style="background-color:#00dba0; border-radius:4px; padding: 5px; text-align:center; margin-left:650px; margin-right:650px;color:white;">-->
<!--    {{object.title}}</h1>-->

<div class="articles">

    <div class="article">
        <div class="article-detail">
            <hr>

            <p><img src="{{articles_detail.category.image.url}}"><span style="margin-left:50px; font-size:2.0em; color:#00dba0">{{object.title}}</span></p>
              <hr style="border:1px solid #00dba0">




            <img src="{{articles_detail.thumb.url}}">

            <hr>
            {% if articles_detail.recipe != None %}
            <hr>
            <p>Recipe: {{ object.recipe}}</p>
            {% endif%}

            <p> Created on {{ object.date }} by <a href="">{{ object.author }}</a></p>
            <hr>


        </div>
    </div>


    <div class="article">
        <div class="article-detail">
            <hr>
            <h2>Content</h2>
                <hr style="border:1px solid #00dba0">
            <p>{{ object.body }}</p>
            <hr>
        </div>
    </div>

    <div class="article">
        <div class="article-detail">
                <hr style="border:1px solid #00dba0">
            <h2>Comments</h2>
             <hr style="border:1px solid #00dba0">
            {% for comment in object.comments.all %}

            {% if user.is_authenticated %}

            {{comment.create_date}}
            <p>{{comment.body}}</p>
            <p>Created on {{comment.date }} by {{comment.author }}</p>
            <hr style="border:1px solid #00dba0">
            {% endif %}
            {% empty %}

            <p>No Comments</p>

            {% endfor %}


                        <nav>

                                <form action="{% url 'web_app:articles_comment' object.id %}">
                    <li>
                       <button style="background-color: #00dba0; color:white; border : 1px solid #00dba0; border-radius:5px; font-size: 1.5em;" type="submit">Comment</button>
                    </li>
                </form>



                {% if object.author == user %}
                <form action="{% url 'web_app:articles_update' object.id %}">
                    <li>
                        <button style="background-color: #00dba0; color:white; border : 1px solid #00dba0; border-radius:5px; font-size: 1.5em;"type="submit">Update</button>
                    </li>
                </form>
                <form action="{% url 'web_app:articles_delete' object.id %}">
                    <li>
                        <button style="background-color: #00dba0; color:white; border : 1px solid #00dba0; border-radius:5px; font-size: 1.5em;"type="submit">Delete</button>
                    </li>
                </form>

                {% endif %}


            </nav>

        </div>
    </div>


</div>


{% endblock %}

website/web_app/templates/articles_list.html
{% extends "base.html" %}
{%  load static from staticfiles %}
{% block body_block %}


<link rel="stylesheet" href="{% static 'web_app/styles.css' %}">


<div class="wrapper">
    <h1 style="background-color:#00dba0; border-radius:4px; padding: 5px; margin-left:650px; margin-right:650px;">LIST OF POSTED ARTICLES</h1>
    <br>
    <br>
    <div class="articles">
        {% for article in articles_list %}
        <div class="article">
            <div class="article-detail">
                <p>
                    <img src="{{article.category.image.url}}">
                    <a style="decoration: none;" href="{% url 'web_app:articles_detail' pk=article.pk %}"><span>  {{article.title}}</span> </a>
                    <hr style="border:1px solid #00dba0">
                </p>
                <p> Created on {{ article.date }} by <a href="{% url 'web_app:user_articles_list' article.author.username %}">{{ article.author }}</a></p>
                <hr>
                <p>{{ article.snippet }}</p>

                <p style="background-color:#00dba0; border-radius:4px; padding: 5px">Number of Comments:
                    {{article.comments.count}}</p>


                {% if article.recipe != None %}

                <p>Recipe: {{ article.recipe}}</p>
                {% endif%}
            </div>
        </div>
        {% endfor %}
        <div class="paginator">
                <div class="article" style="border:none">
                        <div class="article-detail">
                            {% if is_paginated %}
                            {% if page_obj.has_previous %}
                            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number}}">Previous</a>
                            {% endif%}

                            {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                            <a class="btn btn-info mb-4" href="?page={{ num }}">{{num}}</a>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{num}}</a>
                            {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages}}">Last</a>
                            {% endif%}
                            {% endif %}
                        </div>
            </div>
        </div>
    </div>

    {% endblock %}

website/web_app/templates/base.html
<!DOCTYPE html>
{%  load static from staticfiles%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Website</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/static/web_app/styles.css">
</head>

<header>

    <nav>
        <form>

        </form>

        <form action="{% url 'web_app:articles_list' %}">
            <li>
                <button type="submit">Home</button>
            </li>
        </form>

        <form action="{% url 'web_app:recipe_list' %}">
            <li>
                <button type="submit">Recipes</button>
            </li>
        </form>


        <form action="{% url 'web_app:articles_create' %}">
            <li>
                <button class="highlight" type="submit">Create New Article</button>
            </li>
        </form>
        {% if user.is_superuser %}
        <form action="{% url 'web_app:category_create'  %}">
            {% csrf_token%}

            <li>
                <button type="submit">Create New Category</button>
            </li>

        </form>


        <form action="{% url 'web_app:recipe_create'  %}">
            {% csrf_token%}

            <li>
                <button type="submit">Create New Recipe</button>
            </li>

        </form>
        {% endif %}

        {% if user.is_authenticated %}

        <form action="{% url 'accounts:logout'  %}" method="post">
            {% csrf_token%}
            <li>
                <button type="submit">LogOut</button>
            </li>
        </form>
        <form>
            <li>
                <button><span style="margin-left:300px">User:  {{user.username}}</span></button>
            </li>
        </form>
        {% else %}

        <form action="{% url 'accounts:login'  %}" method="post">
            {% csrf_token%}

            <li>
                <button type="submit">LogIn</button>
            </li>

        </form>

        <form action="{% url 'accounts:signup'  %}"> {% csrf_token%}

            <li>
                <button type="submit">SignUp</button>
            </li>

        </form>


        {% endif %}
        <br>

    </nav>
    <li><a href="{% url 'web_app:articles_list' %}"><img src="{% static 'web_app/Look@this.png' %}" width="200px"
                                                             height="200px" alt=""></a></li>
</header>

{% block body_block %}
{% endblock %}


</html>

website/web_app/templates/category_create.html
{% extends "base.html" %}
{% block body_block %}


<div class="site-form">
    <h2>Create a new Category for your Article</h2>
    <hr>
    <!--    enctyp is necessary due to the image upload field-->
    <form class="textarea" action="{% url 'web_app:category_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        {{ form }}
        <input type="submit" value="create">
    </form>
</div>

{% endblock %}

website/web_app/templates/recipe_create.html
{% extends "base.html" %}
{% block body_block %}


<div class="site-form">
    <h2>Create a new Recipe</h2>
    <hr>
    <!--    enctyp is necessary due to the image upload field-->
    <form class="textarea" action="{% url 'web_app:recipe_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token%}
        {{ form }}
        <input type="submit" value="create">
    </form>
</div>

{% endblock %}

website/web_app/templates/recipe_detail.html
<{% extends "base.html" %}
{%  load static from staticfiles %}
{% block body_block %}


<h1 style="background-color:#00dba0; border-radius:4px; padding: 5px; text-align:center; margin-left:650px; margin-right:650px;color:white;">
    {{object.title}}</h1>

<div class="articles">

    <div class="article">
        <div class="article-detail">
            <hr>
            <h1 style="color:#00dba0">{{recipe_detail.title}}</h1>
            <hr>
            <p><img style="width:400px;height:300px" src="{{recipe_detail.image.url}}">
            <hr>
            <h3>{{recipe_detail.subtitle}}</h3>
            <hr style="border: 1px solid #00dba0">
            <h2 style="color:#00dba0">Ingredients</h2>
            <p>{{recipe_detail.ingredients}}</p>
            <hr>
            <h2 style="color:#00dba0">Preparation</h2>
            <p>{{recipe_detail.preparation}}</p>
            <hr>


        </div>
    </div>
</div>


</div>


{% endblock %}

website/web_app/templates/recipe_list.html
{% extends "base.html" %}
{%  load static from staticfiles %}
{% block body_block %}


<body>
<div class="wrapper">
        <h1 style="background-color:#00dba0; border-radius:4px; padding: 5px; margin-left:650px; margin-right:650px;">LIST OF POSTED RECIPES</h1>
    <div class="articles">
        {% for recipe in recipe_list %}
        <div class="article">
            <div class="article-detail">
                {% if recipe.title != 'No Recipe' %}
                <h2><a style="text-decoration:none"  href="{% url 'web_app:recipe_detail' pk=recipe.pk%}">{{recipe.title}}</a></h2>
                               <hr>
                <h3>{{ recipe.subtitle }}</h3>
                <hr>
                <h4>Ingredients</h4>
                <p>{{recipe.ingredients }}</p>
                <h4>Preperation</h4>
                <p>{{ recipe.preparation }}</p>
                {% endif %}
            </div>
        </div>
        {% endfor %}
        <div class="paginator">
            <div class="article" style="border:none">
                <div class="article-detail">
                    {% if is_paginated %}
                    {% if page_obj.has_previous %}
                    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number}}">Previous</a>
                    {% endif%}

                    {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{num}}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{num}}</a>
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages}}">Last</a>
                    {% endif%}
                    {% endif %}
                </div>   </div>

        </div>
    </div>
</div>


{% endblock %}
</body>

website/web_app/templates/user_articles_list.html
{% extends "base.html" %}
{%  load static from staticfiles %}
{% block body_block %}


<link rel="stylesheet" href="{% static 'web_app/styles.css' %}">


<div class="wrapper">
    <h1 style="background-color:#00dba0; border-radius:4px; padding: 5px; margin-left:650px; margin-right:650px;">LIST
        OF POSTED ARTICLES by {{ view.kwargs.username }} ({{ page_obj.paginator.count}}) </h1>
    <br>
    <br>
    <div class="articles">
        {% for article in user_articles_list %}
        <div class="article">
            <div class="article-detail">
                <p>
                   <img src="{{article.category.image.url}}">
                   <a href="{% url 'web_app:articles_detail' pk=article.pk%}"><span>  {{article.title}}</span> </a>
                </p>
                    <hr style="border:1px solid #00dba0">
               <p> Created on {{ article.date }} by <a href="#"> {{ article.author }}</a></p>
                <hr>
                <p>{{ article.snippet }}</p>
                <hr>
                <p style="background-color:#00dba0; border-radius:4px; padding: 5px">Number of Comments:
                    {{article.comments.count}}</p>
                {% if article.recipe != None %}
                <hr>
                <p>Recipe: {{ article.recipe}}</p>
                {% endif%}
            </div>
        </div>
        {% endfor %}
        <div class="paginator">
            <div class="article" style="border:none">
                <div class="article-detail">
                    {% if is_paginated %}
                    {% if page_obj.has_previous %}
                    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number}}">Previous</a>
                    {% endif%}

                    {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{ num }}">{{num}}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                    <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{num}}</a>
                    {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages}}">Last</a>
                    {% endif%}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    {% endblock %}